


import java.awt.Color;
import java.sql.*;
import fms.ConnectionProvider;
import javax.swing.JFrame;
import java.lang.Integer;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jana
 */
public class AddFees extends javax.swing.JFrame {

    /**
     * Creates new form AddFees
     */
    public AddFees() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        fillcomboBox();   
        int receiptno=getReceiptNo();
        trn.setText(Integer.toString(receiptno));
    }
    
    public boolean validation()
    {
        if(trfrom.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"please enter the name of the student payed");
            return false;
        }
        if(tusn.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"please enter the USN");
            return false;
        }
        if(tamount.getText().equals("") || tamount.getText().matches("[0-9]+")==false)
        {
            JOptionPane.showMessageDialog(this,"please enter amount in numbers");
             return false;
        }
           
        return true;
    }
    
    public void fillcomboBox(){
         try{
              Connection conn=ConnectionProvider.getConnection();
              PreparedStatement pst=conn.prepareStatement("select coursename from course");
              ResultSet rs=pst.executeQuery();
              while(rs.next()){
                  combocourse.addItem(rs.getString("coursename"));
              }
         }
        catch(Exception e){
                e.printStackTrace();
                }
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        side1 = new javax.swing.JPanel();
        bh = new javax.swing.JPanel();
        bhome = new javax.swing.JLabel();
        psr = new javax.swing.JPanel();
        bsr = new javax.swing.JLabel();
        pec = new javax.swing.JPanel();
        bec = new javax.swing.JLabel();
        pcl = new javax.swing.JPanel();
        bcl = new javax.swing.JLabel();
        pvar = new javax.swing.JPanel();
        bvar = new javax.swing.JLabel();
        pb = new javax.swing.JPanel();
        bb = new javax.swing.JLabel();
        pl = new javax.swing.JPanel();
        bl = new javax.swing.JLabel();
        mainside = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lupi = new javax.swing.JLabel();
        lbankname = new javax.swing.JLabel();
        trn = new javax.swing.JTextField();
        tupi = new javax.swing.JTextField();
        tbankname = new javax.swing.JTextField();
        combomode = new javax.swing.JComboBox<>();
        panelside2 = new javax.swing.JPanel();
        lreceivefrom = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        combocourse = new javax.swing.JComboBox<>();
        tfromyear = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ttoyear = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tusn = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tparticular = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        amountwords = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tremark = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        bsave = new javax.swing.JButton();
        trfrom = new javax.swing.JTextField();
        ttamount = new javax.swing.JTextField();
        tamount = new javax.swing.JTextField();
        textdate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        side1.setBackground(new java.awt.Color(0, 102, 102));
        side1.setPreferredSize(new java.awt.Dimension(540, 1040));
        side1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bh.setBackground(new java.awt.Color(0, 102, 102));
        bh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bh.setForeground(new java.awt.Color(255, 255, 255));
        bh.setPreferredSize(new java.awt.Dimension(250, 65));
        bh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bhMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bhMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bhMouseReleased(evt);
            }
        });
        bh.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bhome.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bhome.setForeground(new java.awt.Color(255, 255, 255));
        bhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/whome1.jpg"))); // NOI18N
        bhome.setText("HOME");
        bh.add(bhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, -1));

        side1.add(bh, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 260, 60));

        psr.setBackground(new java.awt.Color(0, 102, 102));
        psr.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        psr.setPreferredSize(new java.awt.Dimension(250, 65));
        psr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                psrMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                psrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                psrMouseExited(evt);
            }
        });
        psr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bsr.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bsr.setForeground(new java.awt.Color(255, 255, 255));
        bsr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wsearch.png"))); // NOI18N
        bsr.setText("SEARCH RECORD");
        psr.add(bsr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, -1));

        side1.add(psr, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 260, 60));

        pec.setBackground(new java.awt.Color(0, 102, 102));
        pec.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pec.setPreferredSize(new java.awt.Dimension(250, 5));
        pec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pecMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pecMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pecMouseReleased(evt);
            }
        });
        pec.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bec.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bec.setForeground(new java.awt.Color(255, 255, 255));
        bec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        bec.setText("EDIT COURSE");
        pec.add(bec, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, -1));

        side1.add(pec, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 260, 60));

        pcl.setBackground(new java.awt.Color(0, 102, 102));
        pcl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pcl.setPreferredSize(new java.awt.Dimension(250, 65));
        pcl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pclMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pclMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pclMouseReleased(evt);
            }
        });
        pcl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bcl.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bcl.setForeground(new java.awt.Color(255, 255, 255));
        bcl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wcorse.png"))); // NOI18N
        bcl.setText("COURSE LIST");
        bcl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bclMouseEntered(evt);
            }
        });
        pcl.add(bcl, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 10, 170, -1));

        side1.add(pcl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 260, -1));

        pvar.setBackground(new java.awt.Color(0, 102, 102));
        pvar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pvar.setPreferredSize(new java.awt.Dimension(250, 65));
        pvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pvarMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pvarMouseReleased(evt);
            }
        });
        pvar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bvar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bvar.setForeground(new java.awt.Color(255, 255, 255));
        bvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/report.png"))); // NOI18N
        bvar.setText("VIEW ALL RECORDS");
        pvar.add(bvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        side1.add(pvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 260, -1));

        pb.setBackground(new java.awt.Color(0, 102, 102));
        pb.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pb.setPreferredSize(new java.awt.Dimension(250, 65));
        pb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pbMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pbMouseReleased(evt);
            }
        });
        pb.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bb.setForeground(new java.awt.Color(255, 255, 255));
        bb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wback.png"))); // NOI18N
        bb.setText("BACK");
        pb.add(bb, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 15, 230, 40));

        side1.add(pb, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 260, -1));

        pl.setBackground(new java.awt.Color(0, 102, 102));
        pl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pl.setPreferredSize(new java.awt.Dimension(250, 60));
        pl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                plMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                plMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                plMouseReleased(evt);
            }
        });
        pl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bl.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bl.setForeground(new java.awt.Color(255, 255, 255));
        bl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/log.png"))); // NOI18N
        bl.setText("LOGOUT");
        pl.add(bl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, -1));

        side1.add(pl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, 260, -1));

        mainside.setBackground(new java.awt.Color(153, 255, 255));
        mainside.setPreferredSize(new java.awt.Dimension(1310, 1040));
        mainside.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Reciept No.:");
        mainside.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Mode Of Payment:");
        mainside.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Date:");
        mainside.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        lupi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lupi.setText("UPI Id:");
        mainside.add(lupi, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        lbankname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbankname.setText("Bank Name:");
        mainside.add(lbankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));
        mainside.add(trn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 170, -1));
        mainside.add(tupi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 170, 30));
        mainside.add(tbankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 170, -1));

        combomode.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        combomode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UPI" }));
        combomode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combomodeActionPerformed(evt);
            }
        });
        mainside.add(combomode, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 130, -1));

        panelside2.setBackground(new java.awt.Color(153, 255, 255));
        panelside2.setPreferredSize(new java.awt.Dimension(1010, 300));
        panelside2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lreceivefrom.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lreceivefrom.setText("Received From:");
        panelside2.add(lreceivefrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Payment for the Year:");
        panelside2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Course:");
        panelside2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        combocourse.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        combocourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        combocourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combocourseActionPerformed(evt);
            }
        });
        panelside2.add(combocourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 320, -1));
        panelside2.add(tfromyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 100, -1));

        jLabel10.setText("to");
        panelside2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 20, 20));
        panelside2.add(ttoyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 90, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("USN:");
        panelside2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, -1));
        panelside2.add(tusn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 160, -1));
        panelside2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 770, 10));
        panelside2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 153, 770, 10));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("Serial No.");
        panelside2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText("Particulars");
        panelside2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setText("Amount");
        panelside2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, -1, -1));
        panelside2.add(tparticular, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 320, -1));
        panelside2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 200, 10));

        amountwords.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        panelside2.add(amountwords, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 410, 30));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("Total In Words:");
        panelside2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));
        panelside2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 403, 190, 10));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Remark:");
        panelside2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        tremark.setColumns(20);
        tremark.setRows(5);
        jScrollPane1.setViewportView(tremark);

        panelside2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, -1, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel17.setText("Receivers Signature");
        panelside2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, -1, -1));

        bsave.setBackground(new java.awt.Color(204, 204, 204));
        bsave.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        bsave.setText("SAVE");
        bsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsaveActionPerformed(evt);
            }
        });
        panelside2.add(bsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 130, 40));

        trfrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trfromActionPerformed(evt);
            }
        });
        panelside2.add(trfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 130, -1));
        panelside2.add(ttamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 120, 30));

        tamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamountActionPerformed(evt);
            }
        });
        panelside2.add(tamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 200, 130, 30));

        mainside.add(panelside2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 830, 510));

        textdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        textdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textdateActionPerformed(evt);
            }
        });
        mainside.add(textdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(side1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainside, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(side1, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
            .addComponent(mainside, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bhMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhMouseEntered
         Color clr=new Color(0,153,153);
          bh.setBackground(clr);
          
          // TODO add your handling code here:
    }//GEN-LAST:event_bhMouseEntered

    private void bhMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhMouseExited
 Color clr=new Color(0,103,103);
 bh.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_bhMouseExited

    private void psrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psrMouseEntered
          Color clr=new Color(0,153,153);
          psr.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_psrMouseEntered

    private void pecMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pecMouseEntered
            Color clr=new Color(0,153,153);
          pec.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_pecMouseEntered

    private void bclMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bclMouseEntered
           // TODO add your handling code here:
    }//GEN-LAST:event_bclMouseEntered

    private void pvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pvarMouseEntered
Color clr=new Color(0,153,153);
          pvar.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_pvarMouseEntered

    private void pbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pbMouseEntered
Color clr=new Color(0,153,153);
         pb.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_pbMouseEntered

    private void plMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plMouseEntered
Color clr=new Color(0,153,153);
         pl.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_plMouseEntered

    private void pclMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pclMouseEntered
Color clr=new Color(0,153,153);
          pcl.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_pclMouseEntered

    private void psrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psrMouseExited
 Color clr=new Color(0,103,103);
psr.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_psrMouseExited

    private void pecMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pecMouseExited
 Color clr=new Color(0,103,103);
pec.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_pecMouseExited

    private void pclMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pclMouseExited
  Color clr=new Color(0,103,103);
  pcl.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_pclMouseExited

    private void pvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pvarMouseExited
 Color clr=new Color(0,103,103);
pvar.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_pvarMouseExited

    private void pbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pbMouseExited
 Color clr=new Color(0,103,103);
pb.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_pbMouseExited

    private void plMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plMouseExited
 Color clr=new Color(0,103,103);
pl.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_plMouseExited

    private void combomodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combomodeActionPerformed
        if(combomode.getSelectedIndex()==0)
        {
            //lcheque.setVisible(false);
            lupi.setVisible(true);
            tupi.setVisible(true);
           // tcheque.setVisible(false);
            tbankname.setVisible(true);
            lbankname.setVisible(true);
            //lcard.setVisible(false);
            //tcard.setVisible(false);
        }
        /*else if(combomode.getSelectedIndex()==1)
        {
            lcheque.setVisible(true);
            lupi.setVisible(false);
            tupi.setVisible(false);
            tcheque.setVisible(true);
            tbankname.setVisible(true);
            lbankname.setVisible(true);
            lcard.setVisible(false);
            tcard.setVisible(false);
        }
         else  if(combomode.getSelectedIndex()==2)
        {
            lcheque.setVisible(false);
            lupi.setVisible(false);
            tupi.setVisible(false);
            tcheque.setVisible(false);
            tbankname.setVisible(true);
            lbankname.setVisible(true);
            lcard.setVisible(false);
            tcard.setVisible(false);
        }
         else if(combomode.getSelectedIndex()==3)
        {
            lcheque.setVisible(false);
            lupi.setVisible(false);
            tupi.setVisible(false);
            tcheque.setVisible(false);
            tbankname.setVisible(true);
            lbankname.setVisible(true);
            lcard.setVisible(true);
            tcard.setVisible(true);
        }
       */
    }//GEN-LAST:event_combomodeActionPerformed
     public void setRecordTable()
      {
          String cname=combocourse.getSelectedItem().toString();
          try{
              Connection conn=ConnectionProvider.getConnection();
              PreparedStatement pst=conn.prepareStatement("select fees from course where coursename=?");
              pst.setString(1,cname);
              ResultSet rs=pst.executeQuery();
              while(rs.next()){
                  int fee=rs.getInt("fees");
                  
                  //int sl_no=rs.getInt("courseid");
                  //String Course_name=rs.getString("coursename");
                 // int amount=rs.getInt("fees");
               
                  
                  //Object[] obj={Receipt_no,Student_name,USN,Course,UPI,Bank_name,From_year,To_year,Total_amount,In_words,remarks,date};
                  Object[] obj={fee};
                  tamount.setText(Integer.toString(fee));
                  
                  
                  
              }
          }
          catch(Exception e){
              e.printStackTrace();
          }
      }                                        
   public int getReceiptNo()
   {
       int receiptno = 6;
       try{
            Connection conn=ConnectionProvider.getConnection();
            PreparedStatement pst=conn.prepareStatement("select max(rno) from studentfee");
            ResultSet rs=pst.executeQuery();
            if(rs.next()==true){
                receiptno=rs.getInt(1);
            }
       }
       catch(Exception e)
       {
           e.printStackTrace();
       }
       return receiptno+1;
   }
        
               
                                              
        
            
    private void combocourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combocourseActionPerformed
        tparticular.setText( combocourse.getSelectedItem().toString());
        setRecordTable();
        
        
    }//GEN-LAST:event_combocourseActionPerformed

    private void bsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsaveActionPerformed
          if(validation()==true){
            JOptionPane.showMessageDialog(this,"Validation successfull");
         }
        int rno=Integer.parseInt(trn.getText());
            String upi=tupi.getText();
            //}
            String bankname=tbankname.getText();
            String receivedfrom=trfrom.getText();
            int yearfrom=Integer.parseInt(tfromyear.getText());
            int yearto=Integer.parseInt(ttoyear.getText());
            String course=(String)combocourse.getSelectedItem();
            String USN=tusn.getText();
            int total=Integer.parseInt(tamount.getText());
            String twords=amountwords.getText();
            String remarks=tremark.getText();
            String tdate=textdate.getText();
            try{
                Connection conn=ConnectionProvider.getConnection();
                Statement st=conn.createStatement();
                st.executeUpdate("insert into studentfee values('"+rno+"','"+upi+"','"+bankname+"','"+receivedfrom+"','"+yearfrom+"','"+yearto+"','"+course+"','"+USN+"','"+total+"','"+twords+"','"+remarks+"','"+tdate+"')");
                JOptionPane.showMessageDialog(null,"successfully updated");
                setVisible(false);
                new AddFees().setVisible(true);
            }
            catch(Exception e){
                 JOptionPane.showMessageDialog(null,"updation failed");
                setVisible(false);
               new AddFees().setVisible(true);
                
                
            }
    }//GEN-LAST:event_bsaveActionPerformed

    private void textdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textdateActionPerformed

    private void trfromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trfromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trfromActionPerformed

    private void tamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamountActionPerformed
         Float amount=Float.parseFloat(tamount.getText());
       /* Float concession=(float)(1*200);
        tconcession.setText(concession.toString());*/
       float total=amount;
        ttamount.setText(Float.toString(total));
    }//GEN-LAST:event_tamountActionPerformed

    private void bhMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhMouseReleased
        new home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bhMouseReleased

    private void psrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psrMouseClicked
        new search_record().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_psrMouseClicked

    private void pecMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pecMouseReleased
       new course_details().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_pecMouseReleased

    private void pbMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pbMouseReleased
        new home().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_pbMouseReleased

    private void pclMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pclMouseReleased
       new courselist().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_pclMouseReleased

    private void pvarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pvarMouseReleased
        new ViewAllRecords().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pvarMouseReleased

    private void plMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plMouseReleased
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_plMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountwords;
    private javax.swing.JLabel bb;
    private javax.swing.JLabel bcl;
    private javax.swing.JLabel bec;
    private javax.swing.JPanel bh;
    private javax.swing.JLabel bhome;
    private javax.swing.JLabel bl;
    private javax.swing.JButton bsave;
    private javax.swing.JLabel bsr;
    private javax.swing.JLabel bvar;
    private javax.swing.JComboBox<String> combocourse;
    private javax.swing.JComboBox<String> combomode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbankname;
    private javax.swing.JLabel lreceivefrom;
    private javax.swing.JLabel lupi;
    private javax.swing.JPanel mainside;
    private javax.swing.JPanel panelside2;
    private javax.swing.JPanel pb;
    private javax.swing.JPanel pcl;
    private javax.swing.JPanel pec;
    private javax.swing.JPanel pl;
    private javax.swing.JPanel psr;
    private javax.swing.JPanel pvar;
    private javax.swing.JPanel side1;
    private javax.swing.JTextField tamount;
    private javax.swing.JTextField tbankname;
    private javax.swing.JTextField textdate;
    private javax.swing.JTextField tfromyear;
    private javax.swing.JTextField tparticular;
    private javax.swing.JTextArea tremark;
    private javax.swing.JTextField trfrom;
    private javax.swing.JTextField trn;
    private javax.swing.JTextField ttamount;
    private javax.swing.JTextField ttoyear;
    private javax.swing.JTextField tupi;
    private javax.swing.JTextField tusn;
    // End of variables declaration//GEN-END:variables
}
