
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jana
 */
public class printreceipt extends javax.swing.JFrame {

    /**
     * Creates new form printreceipt
     */
    public printreceipt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        side1 = new javax.swing.JPanel();
        bh = new javax.swing.JPanel();
        bhome = new javax.swing.JLabel();
        psr = new javax.swing.JPanel();
        bsr = new javax.swing.JLabel();
        pec = new javax.swing.JPanel();
        bec = new javax.swing.JLabel();
        pcl = new javax.swing.JPanel();
        bcl = new javax.swing.JLabel();
        pvar = new javax.swing.JPanel();
        bvar = new javax.swing.JLabel();
        pb = new javax.swing.JPanel();
        bb = new javax.swing.JLabel();
        pl = new javax.swing.JPanel();
        bl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side1.setBackground(new java.awt.Color(0, 102, 102));
        side1.setPreferredSize(new java.awt.Dimension(540, 1040));
        side1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bh.setBackground(new java.awt.Color(0, 102, 102));
        bh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bh.setForeground(new java.awt.Color(255, 255, 255));
        bh.setPreferredSize(new java.awt.Dimension(250, 65));
        bh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bhMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bhMouseExited(evt);
            }
        });
        bh.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bhome.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bhome.setForeground(new java.awt.Color(255, 255, 255));
        bhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/whome1.jpg"))); // NOI18N
        bhome.setText("HOME");
        bh.add(bhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, -1));

        side1.add(bh, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 260, 60));

        psr.setBackground(new java.awt.Color(0, 102, 102));
        psr.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        psr.setPreferredSize(new java.awt.Dimension(250, 65));
        psr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                psrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                psrMouseExited(evt);
            }
        });
        psr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bsr.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bsr.setForeground(new java.awt.Color(255, 255, 255));
        bsr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wsearch.png"))); // NOI18N
        bsr.setText("SEARCH RECORD");
        psr.add(bsr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, -1));

        side1.add(psr, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 260, 60));

        pec.setBackground(new java.awt.Color(0, 102, 102));
        pec.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pec.setPreferredSize(new java.awt.Dimension(250, 5));
        pec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pecMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pecMouseExited(evt);
            }
        });
        pec.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bec.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bec.setForeground(new java.awt.Color(255, 255, 255));
        bec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        bec.setText("EDIT COURSE");
        pec.add(bec, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, -1));

        side1.add(pec, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 260, 60));

        pcl.setBackground(new java.awt.Color(0, 102, 102));
        pcl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pcl.setPreferredSize(new java.awt.Dimension(250, 65));
        pcl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pclMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pclMouseExited(evt);
            }
        });
        pcl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bcl.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bcl.setForeground(new java.awt.Color(255, 255, 255));
        bcl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wcorse.png"))); // NOI18N
        bcl.setText("COURSE LIST");
        bcl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bclMouseEntered(evt);
            }
        });
        pcl.add(bcl, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 10, 170, -1));

        side1.add(pcl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 260, -1));

        pvar.setBackground(new java.awt.Color(0, 102, 102));
        pvar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pvar.setPreferredSize(new java.awt.Dimension(250, 65));
        pvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pvarMouseExited(evt);
            }
        });
        pvar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bvar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bvar.setForeground(new java.awt.Color(255, 255, 255));
        bvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/report.png"))); // NOI18N
        bvar.setText("VIEW ALL RECORDS");
        pvar.add(bvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        side1.add(pvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 260, -1));

        pb.setBackground(new java.awt.Color(0, 102, 102));
        pb.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pb.setPreferredSize(new java.awt.Dimension(250, 65));
        pb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pbMouseExited(evt);
            }
        });
        pb.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bb.setForeground(new java.awt.Color(255, 255, 255));
        bb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wback.png"))); // NOI18N
        bb.setText("BACK");
        pb.add(bb, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 15, 230, 40));

        side1.add(pb, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 260, -1));

        pl.setBackground(new java.awt.Color(0, 102, 102));
        pl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pl.setPreferredSize(new java.awt.Dimension(250, 60));
        pl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                plMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                plMouseExited(evt);
            }
        });
        pl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bl.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bl.setForeground(new java.awt.Color(255, 255, 255));
        bl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/log.png"))); // NOI18N
        bl.setText("LOGOUT");
        pl.add(bl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, -1));

        side1.add(pl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, 260, -1));

        getContentPane().add(side1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 471, 933));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("A J INSTITUTE OF ENGINEERING AND TECHNOLOGY");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AJIET.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setText("A Unit of Laxmi Memorial Education Trust(R)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel3)))
                .addContainerGap(399, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(699, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 1230, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bhMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhMouseEntered
        Color clr=new Color(0,153,153);
        bh.setBackground(clr);

        // TODO add your handling code here:
    }//GEN-LAST:event_bhMouseEntered

    private void bhMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhMouseExited
        Color clr=new Color(0,103,103);
        bh.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_bhMouseExited

    private void psrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psrMouseEntered
        Color clr=new Color(0,153,153);
        psr.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_psrMouseEntered

    private void psrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psrMouseExited
        Color clr=new Color(0,103,103);
        psr.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_psrMouseExited

    private void pecMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pecMouseEntered
        Color clr=new Color(0,153,153);
        pec.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_pecMouseEntered

    private void pecMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pecMouseExited
        Color clr=new Color(0,103,103);
        pec.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_pecMouseExited

    private void bclMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bclMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bclMouseEntered

    private void pclMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pclMouseEntered
        Color clr=new Color(0,153,153);
        pcl.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_pclMouseEntered

    private void pclMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pclMouseExited
        Color clr=new Color(0,103,103);
        pcl.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_pclMouseExited

    private void pvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pvarMouseEntered
        Color clr=new Color(0,153,153);
        pvar.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_pvarMouseEntered

    private void pvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pvarMouseExited
        Color clr=new Color(0,103,103);
        pvar.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_pvarMouseExited

    private void pbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pbMouseEntered
        Color clr=new Color(0,153,153);
        pb.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_pbMouseEntered

    private void pbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pbMouseExited
        Color clr=new Color(0,103,103);
        pb.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_pbMouseExited

    private void plMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plMouseEntered
        Color clr=new Color(0,153,153);
        pl.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_plMouseEntered

    private void plMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plMouseExited
        Color clr=new Color(0,103,103);
        pl.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_plMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(printreceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(printreceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(printreceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(printreceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new printreceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bb;
    private javax.swing.JLabel bcl;
    private javax.swing.JLabel bec;
    private javax.swing.JPanel bh;
    private javax.swing.JLabel bhome;
    private javax.swing.JLabel bl;
    private javax.swing.JLabel bsr;
    private javax.swing.JLabel bvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pb;
    private javax.swing.JPanel pcl;
    private javax.swing.JPanel pec;
    private javax.swing.JPanel pl;
    private javax.swing.JPanel psr;
    private javax.swing.JPanel pvar;
    private javax.swing.JPanel side1;
    // End of variables declaration//GEN-END:variables
}
