
import fms.ConnectionProvider;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jana
 */
public class Report extends javax.swing.JFrame {
 DefaultTableModel model;
    /**
     * Creates new form Report
     */
    public Report() {
        initComponents();
       setExtendedState(JFrame.MAXIMIZED_BOTH);
       fillcomboBox();
    }
     
    public void fillcomboBox(){
         try{
              Connection conn=ConnectionProvider.getConnection();
              PreparedStatement pst=conn.prepareStatement("select coursename from course");
              ResultSet rs=pst.executeQuery();
              while(rs.next()){
                  coursecombo.addItem(rs.getString("coursename"));
              }
         }
        catch(Exception e){
                e.printStackTrace();
                }
         
    }
   
    public void clear(){
        DefaultTableModel model=(DefaultTableModel)recordtable.getModel();
        model.setRowCount(0);
    }
    public void setRecordTable()
      {
          String cname=coursecombo.getSelectedItem().toString();
          int fyear =Integer.parseInt(fromyear.getText());
          int tyear=Integer.parseInt(toyear.getText());
          int amountTotal=0;
          try{
              Connection conn=ConnectionProvider.getConnection();
              PreparedStatement pst=conn.prepareStatement("select *from studentfee where yearfrom=? and yearto=? and course=?");
              pst.setInt(1,fyear);
              pst.setInt(2,tyear);
              pst.setString(3,cname);
              ResultSet rs=pst.executeQuery();
              while(rs.next()){
                  int Receipt_no=rs.getInt("rno");
                  String Student_name=rs.getString("receivedfrom");
                  String USN=rs.getString("USN");
                  String Course=rs.getString("course");
                  //String UPI=rs.getString("UPI");
                 // String Bank_name=rs.getString("bankname");
                 // int From_year=rs.getInt("yearfrom");
                //  int To_year=rs.getInt("yearto");
                  int Total_amount=rs.getInt("total");
                  //String In_words=rs.getString("twords");
                  String remarks=rs.getString("remarks");
                 // String date=rs.getString("tdate")
                  
                  Object[] obj={Receipt_no,USN,Student_name,Course,Total_amount,remarks};
                  model=(DefaultTableModel)recordtable.getModel();
                  model.addRow(obj);
                 
                  
                  
              }
          }
          catch(Exception e){
              e.printStackTrace();
          }
      }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        side1 = new javax.swing.JPanel();
        bh = new javax.swing.JPanel();
        bhome = new javax.swing.JLabel();
        psr = new javax.swing.JPanel();
        bsr = new javax.swing.JLabel();
        pec = new javax.swing.JPanel();
        bec = new javax.swing.JLabel();
        pcl = new javax.swing.JPanel();
        bcl = new javax.swing.JLabel();
        pvar = new javax.swing.JPanel();
        bvar = new javax.swing.JLabel();
        pb = new javax.swing.JPanel();
        bb = new javax.swing.JLabel();
        pl = new javax.swing.JPanel();
        bl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        coursecombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        browsebutton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tbrowse = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        recordtable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tcs = new javax.swing.JLabel();
        toyear = new javax.swing.JTextField();
        fromyear = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side1.setBackground(new java.awt.Color(0, 102, 102));
        side1.setPreferredSize(new java.awt.Dimension(540, 1040));
        side1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bh.setBackground(new java.awt.Color(0, 102, 102));
        bh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bh.setForeground(new java.awt.Color(255, 255, 255));
        bh.setPreferredSize(new java.awt.Dimension(250, 65));
        bh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bhMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bhMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bhMouseReleased(evt);
            }
        });
        bh.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bhome.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bhome.setForeground(new java.awt.Color(255, 255, 255));
        bhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/whome1.jpg"))); // NOI18N
        bhome.setText("HOME");
        bh.add(bhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, -1));

        side1.add(bh, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 60));

        psr.setBackground(new java.awt.Color(0, 102, 102));
        psr.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        psr.setPreferredSize(new java.awt.Dimension(250, 65));
        psr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                psrMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                psrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                psrMouseExited(evt);
            }
        });
        psr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bsr.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bsr.setForeground(new java.awt.Color(255, 255, 255));
        bsr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wsearch.png"))); // NOI18N
        bsr.setText("SEARCH RECORD");
        psr.add(bsr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, -1));

        side1.add(psr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 260, 60));

        pec.setBackground(new java.awt.Color(0, 102, 102));
        pec.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pec.setPreferredSize(new java.awt.Dimension(250, 5));
        pec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pecMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pecMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pecMouseReleased(evt);
            }
        });
        pec.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bec.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bec.setForeground(new java.awt.Color(255, 255, 255));
        bec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        bec.setText("EDIT COURSE");
        pec.add(bec, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, -1));

        side1.add(pec, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 260, 60));

        pcl.setBackground(new java.awt.Color(0, 102, 102));
        pcl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pcl.setPreferredSize(new java.awt.Dimension(250, 65));
        pcl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pclMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pclMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pclMouseReleased(evt);
            }
        });
        pcl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bcl.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bcl.setForeground(new java.awt.Color(255, 255, 255));
        bcl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wcorse.png"))); // NOI18N
        bcl.setText("COURSE LIST");
        bcl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bclMouseEntered(evt);
            }
        });
        pcl.add(bcl, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 10, 170, -1));

        side1.add(pcl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 260, -1));

        pvar.setBackground(new java.awt.Color(0, 102, 102));
        pvar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pvar.setPreferredSize(new java.awt.Dimension(250, 65));
        pvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pvarMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pvarMouseReleased(evt);
            }
        });
        pvar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bvar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bvar.setForeground(new java.awt.Color(255, 255, 255));
        bvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/report.png"))); // NOI18N
        bvar.setText("VIEW ALL RECORDS");
        pvar.add(bvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        side1.add(pvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 260, -1));

        pb.setBackground(new java.awt.Color(0, 102, 102));
        pb.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pb.setPreferredSize(new java.awt.Dimension(250, 65));
        pb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pbMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pbMouseExited(evt);
            }
        });
        pb.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bb.setForeground(new java.awt.Color(255, 255, 255));
        bb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wback.png"))); // NOI18N
        bb.setText("BACK");
        pb.add(bb, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 15, 230, 40));

        side1.add(pb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 260, -1));

        pl.setBackground(new java.awt.Color(0, 102, 102));
        pl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pl.setPreferredSize(new java.awt.Dimension(250, 60));
        pl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                plMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                plMouseExited(evt);
            }
        });
        pl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bl.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bl.setForeground(new java.awt.Color(255, 255, 255));
        bl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/log.png"))); // NOI18N
        bl.setText("LOGOUT");
        pl.add(bl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, -1));

        side1.add(pl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 260, -1));

        getContentPane().add(side1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 283, 1127));

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 0, 862, -1));

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("Select course:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        coursecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursecomboActionPerformed(evt);
            }
        });
        jPanel2.add(coursecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 280, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setText("Select date:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 90, 20));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel3.setText("to year:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel4.setText("from year:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        browsebutton.setBackground(new java.awt.Color(0, 51, 51));
        browsebutton.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        browsebutton.setForeground(new java.awt.Color(255, 255, 255));
        browsebutton.setText("BROWSE");
        browsebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browsebuttonActionPerformed(evt);
            }
        });
        jPanel2.add(browsebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 51, 51));
        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("PRINT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));
        jPanel2.add(tbrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 210, -1));

        jButton3.setBackground(new java.awt.Color(0, 51, 51));
        jButton3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("SUBMIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        recordtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Receipt no", "USN", "Student name", "Course", "Amount", "Remark"
            }
        ));
        jScrollPane1.setViewportView(recordtable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 840, -1));

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 90, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Course selected:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, -1));

        tcs.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(tcs, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 280, 20));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 470, 40));
        jPanel2.add(toyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 90, -1));
        jPanel2.add(fromyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 80, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 1150, 1120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bhMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhMouseEntered
        Color clr=new Color(0,153,153);
        bh.setBackground(clr);

        
    }//GEN-LAST:event_bhMouseEntered

    private void bhMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhMouseExited
        Color clr=new Color(0,103,103);
        bh.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_bhMouseExited

    private void bhMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhMouseReleased
        new home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bhMouseReleased

    private void psrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psrMouseClicked
        new search_record().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_psrMouseClicked

    private void psrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psrMouseEntered
        Color clr=new Color(0,153,153);
        psr.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_psrMouseEntered

    private void psrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psrMouseExited
        Color clr=new Color(0,103,103);
        psr.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_psrMouseExited

    private void pecMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pecMouseEntered
        Color clr=new Color(0,153,153);
        pec.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_pecMouseEntered

    private void pecMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pecMouseExited
        Color clr=new Color(0,103,103);
        pec.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_pecMouseExited

    private void pecMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pecMouseReleased
        new course_details().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pecMouseReleased

    private void bclMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bclMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bclMouseEntered

    private void pclMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pclMouseEntered
        Color clr=new Color(0,153,153);
        pcl.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_pclMouseEntered

    private void pclMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pclMouseExited
        Color clr=new Color(0,103,103);
        pcl.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_pclMouseExited

    private void pvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pvarMouseEntered
        Color clr=new Color(0,153,153);
        pvar.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_pvarMouseEntered

    private void pvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pvarMouseExited
        Color clr=new Color(0,103,103);
        pvar.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_pvarMouseExited

    private void pbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pbMouseEntered
        Color clr=new Color(0,153,153);
        pb.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_pbMouseEntered

    private void pbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pbMouseExited
        Color clr=new Color(0,103,103);
        pb.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_pbMouseExited

    private void plMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plMouseEntered
        Color clr=new Color(0,153,153);
        pl.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_plMouseEntered

    private void plMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plMouseExited
        Color clr=new Color(0,103,103);
        pl.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_plMouseExited

    private void coursecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursecomboActionPerformed
       tcs.setText( coursecombo.getSelectedItem().toString());
    }//GEN-LAST:event_coursecomboActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          clear();
        setRecordTable();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int yearfrom =Integer.parseInt(fromyear.getText());
          int yearto=Integer.parseInt(toyear.getText());
        MessageFormat header=new MessageFormat("Report From "+yearfrom+" To " +yearto);
MessageFormat footer=new MessageFormat("page{0,number,integer}");
        try {
            recordtable.print(JTable.PrintMode.FIT_WIDTH, header, footer);
            
        } catch (Exception e) {
            e.getMessage();
        } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pclMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pclMouseReleased
        new courselist().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pclMouseReleased

    private void pvarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pvarMouseReleased
        new ViewAllRecords().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pvarMouseReleased

    private void pbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pbMouseClicked
      new home().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_pbMouseClicked

    private void plMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plMouseClicked
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_plMouseClicked
public void search(String str){
            model=(DefaultTableModel)recordtable.getModel();
            TableRowSorter<DefaultTableModel> trs=new TableRowSorter<>(model);
            recordtable.setRowSorter(trs);
            trs.setRowFilter(RowFilter.regexFilter(str));
            
      }
    private void browsebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browsebuttonActionPerformed
         String searchstring=tbrowse.getText();
       search(searchstring);
    }//GEN-LAST:event_browsebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bb;
    private javax.swing.JLabel bcl;
    private javax.swing.JLabel bec;
    private javax.swing.JPanel bh;
    private javax.swing.JLabel bhome;
    private javax.swing.JLabel bl;
    private javax.swing.JButton browsebutton;
    private javax.swing.JLabel bsr;
    private javax.swing.JLabel bvar;
    private javax.swing.JComboBox<String> coursecombo;
    private javax.swing.JTextField fromyear;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pb;
    private javax.swing.JPanel pcl;
    private javax.swing.JPanel pec;
    private javax.swing.JPanel pl;
    private javax.swing.JPanel psr;
    private javax.swing.JPanel pvar;
    private javax.swing.JTable recordtable;
    private javax.swing.JPanel side1;
    private javax.swing.JTextField tbrowse;
    private javax.swing.JLabel tcs;
    private javax.swing.JTextField toyear;
    // End of variables declaration//GEN-END:variables
}
